# Generated by Django 4.2.26 on 2025-11-23 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', max_length=20)),
                ('vendor_name', models.CharField(blank=True, max_length=200)),
                ('vendor_contact', models.CharField(blank=True, max_length=200)),
                ('vendor_address', models.TextField(blank=True)),
                ('requested_delivery_date', models.DateField(blank=True, null=True)),
                ('cost_center', models.CharField(blank=True, max_length=50)),
                ('gl_account', models.CharField(blank=True, max_length=50)),
                ('budget_code', models.CharField(blank=True, max_length=50)),
                ('project_code', models.CharField(blank=True, max_length=50)),
                ('business_justification', models.TextField(blank=True)),
                ('proforma', models.FileField(blank=True, null=True, upload_to='proformas/')),
                ('quotation_comparison', models.FileField(blank=True, null=True, upload_to='quotations/')),
                ('specification_sheet', models.FileField(blank=True, null=True, upload_to='specifications/')),
                ('purchase_order', models.FileField(blank=True, null=True, upload_to='purchase_orders/')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'purchase_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_level', models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2')])),
                ('approved', models.BooleanField()),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals_given', to=settings.AUTH_USER_MODEL)),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='purchases.purchaserequest')),
            ],
            options={
                'db_table': 'approvals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['status'], name='purchase_re_status_d2f181_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['created_by'], name='purchase_re_created_db6402_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['created_at'], name='purchase_re_created_48eac4_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['urgency'], name='purchase_re_urgency_6a8781_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='approval',
            unique_together={('purchase_request', 'approval_level')},
        ),
    ]
