# Generated by Django 4.2.26 on 2025-11-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_purchaseorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='po_data_file',
            field=models.JSONField(blank=True, help_text='Detailed PO data in JSON format', null=True),
        ),
    ]
